name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout código fuente
      uses: actions/checkout@v2

    - name: Verificar versión de Java
      run: java -version

