on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout código fuente
      uses: actions/checkout@v2

    - name: Ejecutar instalador JDK
      run: |
        .\jdk-6u45-windows-x64.exe /s

    - name: Configurar JAVA_HOME y PATH
      run: |
        setx JAVA_HOME "C:\Program Files\Java\jdk1.6.0_45" /M
        setx PATH "%JAVA_HOME%\bin;%PATH%" /M
      shell: cmd

    - name: Verificar versión de Java
      run: java -version

